name: OpenRV Windows

on:
  workflow_dispatch:
    inputs:
      SKIP_DEPS_CACHE:
        description: 'Skip dependencies caching'
        required: true
        default: 'false'

jobs:
  windows:
    uses: ./.github/workflows/ci-windows.yml
    with:
      skip_deps_cache: ${{ inputs.SKIP_DEPS_CACHE || 'false' }}
      full_matrix: 'false'
      run_debug: 'false'
